### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#1]
I have some questions:
- how are we going to maintain vexflow4 and vexflow5 in two repos or one repo with two branches? I would prefer one repo with branches.
- should we delete or update the copyright line from the source files?
- I would move the gonville generation repo to this org if this is ok. Is it? The vexflow5 alpha have reveal a lot of bugs in the font that I have to correct. By the way I have improved the glyphs inspector including all the fonts and glyphs.
- @ronyeh we need, I believe a vexflow-fonts repo with all the used fonts.
- why is the repo private and not forkable?

**Comment by ronyeh** [comment]
Hi Rodrigo!

I am putting some of the migration details here:
https://github.com/0xfe/vexflow/issues/1498#issuecomment-1619140548

I think doing a hard fork into a new repo is a cleaner way to move forward, and will allow us to move faster without worrying as much about breaking prior APIs. You mentioned before that VexFlow 5 will basically be a "new product" so this method (even with its drawbacks) will allow us to treat it as such.

https://github.com/vexflow/vexflow is now public :-) and can be forked. Let's move your vexflow5 branch over to your fork, so we can start submitting PRs and reviewing each others' work.

I know you and both did a lot of camelCase and other explorations, so hopefully we ended up with identical files in many cases! :-)

**Comment by ronyeh** [comment]
Re: vexflow-fonts... Right now the fonts are contained inside this repo, but I agree it might be better to separate them out. We can do that later on in this migration, so that you can include copies of all SMuFL fonts (as long as we include their LICENSE information that specifies the font files are redistributable).

**Comment by rvilarl** [comment]
@ronyeh the repo is not starting from 4.2.2 it is starting from your vexflow 5 branch. I believe that the plan is to also maintain 4.x here, is that right? Should we start from the last version of 0xfe/vexflow set a branch vexflow4.x there and start including all the changes using PRs? Any change required to 4.x we would do in the vexflow4.x branch and no more changes in 0xfe/vexflow

**Comment by ronyeh** [comment]
Sorry for the confusion. 

https://github.com/vexflow/vexflow/commits/main

The repo starts from the 4.2.2 release that I made today, which includes the PR you merged recently.

I did a force-push today to make sure this repo branched off directly from the VexFlow 4.x repo. (You might have looked at it last night, when this repo was in a more experimental state.)

We can verify that both repos contain the same hash:

```
https://github.com/vexflow/vexflow/commit/58206a6336c57aface6949628e8a8f9295564647

https://github.com/0xfe/vexflow/commit/58206a6336c57aface6949628e8a8f9295564647
```

**Comment by ronyeh** [comment]
I'd say we can just leave 4.x at the 0xfe repo, and continue working here on version 5.0+.

If we discover a very high priority bug fix, we can just apply it to the 0xfe repo.

As you mentioned before, 5.0+ will include lots of major breaking changes, so it should be considered a "new product". 

Version 4.x can remain in its previous home.

We will make sure all the necessary tags are in this repo, for future reference: https://github.com/vexflow/vexflow/tags

**Comment by rvilarl** [comment]
You are right, I had the version from last night. :)

**Comment by rvilarl** [comment]
I

**Comment by ronyeh** [comment]
Looking forward to seeing your work on the fonts!

(If it's OK with you, can I submit my camelCase stuff first?) It should be identical to your files... :-)
