### ISSUE TITLE
test infrastructure does not support font names with spaces

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#111]
The task checking the differences does not contruct the names properly:

Warning: Three_Voice_Rests.Three_Voices____1.Finale.png missing in ./build/images/current.

@ronyeh, can you look into that?

**Comment by ronyeh** [comment]
Been busy recently. If you have time, please give it a try. :-) If you get stuck let me know.

**Comment by rvilarl** [comment]
This is now resolved
