### ISSUE TITLE
Release 5.0.0

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#130]
@jaredjj3 has tested now a lot with https://github.com/stringsync/vexml

We will wait to get the font improvements from @ronyeh in #98 

What else should we plan before making the first release?

**Comment by ronyeh** [comment]
Once we get the font improvements in, I'd like to move to a beta release so we can all test with various apps and example jsfiddles.

The more we test, the more confident we will be for releasing 5.0.

**Comment by ronyeh** [comment]
I added this comment in the main VexFlow 5 discussion thread:

https://github.com/vexflow/vexflow/issues/13#issuecomment-1777614163

> Next steps:
> 
> * We should work with Simon Tatham to get an official SMuFL build of Gonville integrated into VexFlow.
> * I'll work on improving the API to `VexFlow.*` instead of `Vex.Flow.*`  [VexFlow instead of Vex.Flow #136](https://github.com/vexflow/vexflow/issues/136)
> * We should review outstanding bugs https://github.com/vexflow/vexflow/issues/ and fix them if they are high enough priority.
> 
> After these three, we can promote V5 from Alpha ⇨ Beta.
> 
> Once in Beta we should advertise it more and ask developers to try it out so we can find and fix bugs and head toward the full release.
> 
> During Beta:
> 
> * Improve README, tutorial, and documentation.
> * Add more to the vexflow-examples repo. We can even list external projects like vexml.
> * Review the vexflow code to improve internal comments (I'm sure many are now out of date).
> * Improve flow.html to speed up rendering (or allow the developer to easily choose which fonts to test).

Let's move our discussion over to that thread for now. 

Once we are closer to an actual release, we can reopen this issue to discuss the details of the 5.0.0 release.

I'll close this issue for now. (To be revisited later.)
