### ISSUE TITLE
VexFlow instead of Vex.Flow

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow#136]
One of the major goals of v5 is to clean up old / unused code and modernize the library, so that a new developer will enjoy the "getting started" experience.

Currently we have a `vex.ts` file that contains some utility methods that were useful a decade ago, but can be removed from v5.

For example:
- `contains(arr: any[], obj: any): boolean // Check if array arr contains obj.`

I assume Mohit had plans for other projects that would all eventually be collected under the `Vex.*` namespace (e.g., Vex.Tab)?

However, for a new user of VexFlow, it feels odd that the main `vex.ts` file doesn't actually have anything useful, and that it imports a Flow object from `flow.ts`.

My proposal (only if @0xfe is OK with it):

- Merge vex.ts and flow.ts into a single file: `vexflow.ts`
- This file exports the class `VexFlow`
- Instead of calling methods like `Vex.Flow.setFonts(...)`, we will write `VexFlow.setFonts(...)`.
- Remove unnecessary utility methods like `contains()`.
- If there are utility methods we need to keep, move them to `util.ts`

What do you all think?

**Comment by 0xfe** [comment]
Fully on board!
