### ISSUE TITLE
Should the CommonMetrics class be in its own file? 

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#14]
To be decided once vexflow5 alpha 0 is reviewed.

**Comment by ronyeh** [comment]
First discussed here:

**Comment by rvilarl** [comment]
I know you care a bit :-) about how big the final library will be. This is obviously premature optimization, but later on, if we discover that our minimizer leaves all these strings intact, it might be fun to have a local variable internal to a common_metrics.ts file that declares `'Times New Roman, serif'` and `'Arial, sans-serif'` so that CommonMetrics can just reference those internal variables.

_Originally posted by @ronyeh in https://github.com/vexflow/vexflow/pull/18#discussion_r1258831967_

**Comment by rvilarl** [comment]
This class could also have the lookupmetrics member function and make it available to the users, removing the need to import tables on tests.

**Comment by rvilarl** [comment]
Followed up in #78
