### ISSUE TITLE
How to import a typed VexFlow object to typescript

### ISSUE THREAD

**Issue by AaronDavidNewman** [vexflow/vexflow#154]
I admit this may be just my ignorance on the best way to do this, as it isn't specifically a vexflow problem.  But I used to (4.2.2) be able to go:

vex.ts:
``` typescript
import { Vex as SmoVex } from "vexflow";  // assume this is the package with name vexflow in my package.config
export type Vex = SmoVex;
export const Vex = SmoVex;
const VF = SmoVex.Flow;
```
VF would have the type of Vex.Flow class, any other module could import it from vex.ts, and I could make objects by going `new VF.StaveNote`, etc, and the StaveNote type stuff would be known by my environment and also webpack.

With the vexflow object, this now longer works.  I suspect this is because VexFlow is exported as default, where before the entry point had `export * as default`.  I admit I've always been a little squishy on how this works.  I can go:

``` typescript
declare var VexFlow: any;
```
and use VexFlow, but it now has type any.  If I go:

``` typescript
import { default as VexFlow } from 'vexflow';

const note = new VexFlow.StaveNote(...);
```

This compiles fine, but at run time VexFlow is not defined so I get an error here (StaveNote not member of undefined).

**Comment by ronyeh** [comment]
H!

We definitely need to improve our examples and documentation before we release 5.0.

For now the 5.0 branch is released as `vxflw-early-access`: https://www.npmjs.com/package/vxflw-early-access

Does this work?

```
import { VexFlow, Factory, Stave, EasyScore } from "vxflw-early-access";
```

So it should look similar to the first line, except instead of `Vex`, it is now `VexFlow`.

**Comment by AaronDavidNewman** [comment]
OK, thanks.  I am able to do this with the early access package.
