### ISSUE TITLE
Dotted slurs are not available

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#157]
See measure 3

![image](https://github.com/vexflow/vexflow/assets/22865285/32963e19-1adf-4b11-bdcd-86c7e0c423cc)

**Comment by rvilarl** [comment]
@mscuthbert are dotted slurs common?

**Comment by mscuthbert** [comment]
They're pretty common (along with dotted ties) in some traditions and instruments. Timpani and snare rolls sometimes use them as do violin tremolos. Not all composers and presses use them but some do to mean "conceptually tied/slurred" even though in reality notes are being rearticulated

**Comment by rvilarl** [comment]
> They're pretty common (along with dotted ties) in some traditions and instruments. Timpani and snare rolls sometimes use them as do violin tremolos. Not all composers and presses use them but some do to mean "conceptually tied/slurred" even though in reality notes are being rearticulated

Thanks! I will go for them then.

**Comment by rvilarl** [comment]
@mscuthbert @AaronDavidNewman @sschmidTU @ronyeh @jaredjj3 @0xfe
The curves are now rendered using two lines this allows to specify a thickness. Is anyone using this?

![svg_Curve Simple_Curve Bravura svg_reference](https://github.com/vexflow/vexflow/assets/22865285/defe2896-2d39-46d6-8905-fffe252dba5c)

This implementation does not allow to use stroke-dasharray. 

Would it be fine to move to a single line implementation that would allow the usage of the dasharray?

![svg_Curve Simple_Curve Bravura svg_current](https://github.com/vexflow/vexflow/assets/22865285/21464ed0-b19f-4ab3-87a1-96a0a61cc296)

The line width above is 1, it could be increased.

**Comment by 0xfe** [comment]
The two lines allow for curves that taper at the ends, which is more consistent with how they're typically seen on sheets. Also, non-dotted curves are overwhelmingly the common case, so we shouldn't change our entire implementation to support it.

Instead, maybe create a separate LineCurve element for those corner cases? Or add an option to the existing Curve that uses a single line. (I prefer a separate element, but not a strong opinion.)

**Comment by rvilarl** [comment]
Hi Mohit, I have to say that I liked more the single line :) . Here now with 2 points. I think that it also reduces the complexity.

![svg_Curve Simple_Curve Bravura svg_current](https://github.com/vexflow/vexflow/assets/22865285/d891c9db-1912-4a14-a02e-9dc2cf9d626b)

The dotted line with two lines looks quite bad, I think

![svg_Curve Simple_Curve Bravura svg_current](https://github.com/vexflow/vexflow/assets/22865285/b5de3f83-1718-4102-8efa-bf12b52b2786)

I will go for an implementation that will only select single line if the dotted style is selected.

**Comment by rvilarl** [comment]
@0xfe do you find this result ok?

![canvas_Curve Simple_Curve Bravura_current](https://github.com/vexflow/vexflow/assets/22865285/cd614fae-e1ad-42bc-a855-f81534529400)

**Comment by 0xfe** [comment]
Yes, that looks good!
