### ISSUE TITLE
ElementStyle infrastructure is not consistent

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#161]
Looking at the dasharray I have realized that the styles are not coded consistently.
I will try to make some PRs without visual differences, starting with Bend.

**Comment by rvilarl** [comment]
This is the current representation of Bend. Is it intentional that the curves are grey and the text and arrow black? I would expect the curves and arrow to be the same color. In the examples I see in interneet, the three elements have the same color. @mscuthbert @AaronDavidNewman what do you think? 

same colour, perhaps too light
![svg_Bend Bend_Phrase Bravura svg_current](https://github.com/vexflow/vexflow/assets/22865285/32fd3da6-fb5a-46ef-ba71-bafa2a6f2348)

reference (currently in the lib)
![svg_Bend Bend_Phrase Bravura svg_reference](https://github.com/vexflow/vexflow/assets/22865285/803a504e-7c67-49c2-977c-ba0d2719eae1)

**Comment by sschmidTU** [comment]
It was apparently already grey+black in Vexflow 1.2.93, not sure if that's relevant.
<img width="362" alt="image" src="https://github.com/vexflow/vexflow/assets/33069673/8d1e39ab-5b3c-457d-872f-21b0d4bf47f3">
I haven't heard complaints about it and I think it looks nice. The curves don't need to be black/bold in my opinion, that might make them overexaggerated, they are well readable as is.

**Comment by mscuthbert** [comment]
I love it how it is -- I think that for the most part, VexFlow should try to emulate standard music notation, but it should also realize that it is designed to be displayed on color computer screens so where it can take advantage of that to make notation more beautiful, I think it's a great idea.  Large symbols that can obscure reading other symbols (like the staff and the bends) are great candidates for gray.  I even wonder if slurs could default to a (dark) gray to make them take less visual space and distinguish them from ties?
