### ISSUE TITLE
Bounding boxes have bugs

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#164]
A set of Bounding Box testing would be good.

**Comment by rvilarl** [comment]
@jaredjj3 l have fixed a few, let me know if you find elements with wrong bounding boxes.

**Comment by jaredjj3** [comment]
@rvilarl, thanks for working on this! FWIW, I'm also doing collision work in https://github.com/stringsync/vexml/pull/227 (detecting point collisions amongst several bounding boxes). Maybe you'll find some useful utilities there.

On https://vexml.dev, there are collisions in the 31a-Directions.musicxml example in measures 6, 9, 10, 11, 14.

![vexml_dev_0_0_0 (9)](https://github.com/vexflow/vexflow/assets/19232300/7d598587-0de1-4040-897a-834bfc237cd6)

**Comment by rvilarl** [comment]
@jaredjj3 I know you are working on it and this is  why I asked :)

In the score above I think that:
- 6 is related to not having a stave which is long enough
- the others relate to #206 , right?

**Comment by jaredjj3** [comment]
Yes I agree on both points.
