### ISSUE TITLE
Comments on #12

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow#17]
Hi Rodrigo!

I wasn't finished reviewing [PR #12](https://github.com/vexflow/vexflow/pull/12). I needed more time to review each file.

Sorry, I should have been more clear. In the future, could you wait for a "Looks Good To Me / LGTM" before merging? Or you could provide your feedback or address the comments I made and then I can go ahead and merge.

I understand that you have been working on your approach for a while now, but to the rest of us who are also interested in VexFlow, some of the concepts and the specific approach you took are completely new information. I personally trust that you made good design decisions, but we all need just a bit more time to process this new information (and ideally, to read through each line of code you wrote).

You're a maintainer of VexFlow 5, so of course you can go ahead and merge any and all PRs you wish. But if you don't give folks like Michael, Mohit, myself, Aaron, Simon, Greg, etc a chance to comment on or review your work, VexFlow 5 might ultimately end up being "Rodrigo's branch" and everyone else might hesitate to upgrade from VexFlow 4.x.

_Originally posted by @ronyeh in https://github.com/vexflow/vexflow/issues/12#issuecomment-1629342448_

**Comment by ronyeh** [comment]
I'm done reviewing your PR. 

My biggest concern is that lookupMetric isn't easy for me to understand. Can you explain the big idea there? Maybe we could simplify it if we structured CommonMetrics slightly differently, or if we broke up the lookupMetrics into parts. I'm not sure why the for loop nested inside the while loop is required.

https://github.com/vexflow/vexflow/pull/18#discussion_r1258766668

**Comment by ronyeh** [comment]
Also, it looks like VexFlow 5 requires an environment where measureText(...) is available. That is OK, but will break certain use cases of VexFlow (i.e., where canvas is not available). We should keep that in the back of our minds, so that maybe we can restore that functionality at some point. Some of the `vexflow/demos/` show off how vexflow can be used outside of the browser (node, JSDOM, SVG) and it is possible that those environments don't have measureText(...). 

If we wanted to someday restore that functionality, would we have to parse the font file (the opentype.js approach)?

**Comment by rvilarl** [comment]
Have you looked into the opentype.js approach? I suggested once to use opentype.js directly but Mohit requested not to have external dependencies.

**Comment by ronyeh** [comment]
I see you addressed my most recent comments. Have all your changes been pushed to the PR? I can merge it later tonight and then we can discuss the two open topics:

1) Improve lookupMetric() and CommonMetrics to be easier to understand and more concise if possible.
2) Think about a backup plan for when measureText() is not available. Even if it's slower performance wise, it would be amazing to (someday) be able to extract the glyphs from the font at runtime and draw the paths like we used to in VexFlow 4. We could let this be an optional plugin that would require opentype.js. So VexFlow by itself would not have an external dependency, but if the developer chooses to add the optional plugin, it would then require opentype.js.

**Comment by rvilarl** [comment]
PR is now there
