### ISSUE TITLE
Feedback on VexFlow tutorial step 3

### ISSUE THREAD

**Issue by stevage** [vexflow/vexflow#172]
I've been rewriting some code to switch from using EasyFlow to using VexFlow directly.

Steps 1 and 2 of the tutorial were great.

Step 3 is pretty confusing.

For some reason, it switches from using the previously introduced approach of instantiating a `Formatter` object and calling `joinVoices` etc to using this:

> `Formatter.FormatAndDraw(context, stave, notes);`

It's confusing because:

- it doesn't tell you what `Formatter` is (and it's pretty ambiguous - is it the name of a module, a class, an object? turns out basically yes, all of the above)
- it doesn't really explain how it works or which "plumbing" it is helping with exactly
- suddenly we don't have access to the `Voice` objects we had been using previously. 
- overall it's a backwards step for the user, because we showed them, the way with power and flexibility, and now we're giving them the mode with training wheels

When I then tried to use the old way to draw a dotted note (the main purpose of step 3), it didn't work, and I got the unhelpful error message that there weren't enough notes for my stave. So there is something happening in `FormatAndDraw` that makes dotted modifiers work that wasn't happening in step 2, that isn't actually explained.

It was only by looking very closely at [the source code for `FormatAndDraw`](https://github.com/0xfe/vexflow/blob/master/src/formatter.ts#L287) that I found the answer:

> `.setMode(Voice.Mode.SOFT).`

I don't actually know what this does (it's not explained in the code), but this apparently makes the durations of dotted notes get calculated properly.

So, suggestions:

- for step 3 and onwards, keep with the original approach, don't suddenly switch to FormatAndDraw. (Which honestly I don't think is very useful for someone who has come this far - it saves you a couple of lines of code but locks you into a single-voice, 4/4 stave which is pretty limiting)
- explain what `Mode.SOFT` is

This step also rather unhelpfully only tells you the manual way of creating accidentals, so I updated it to point to `Accidental.applyAccidentals()` which is pretty hard to find otherwise.

**Comment by AaronDavidNewman** [comment]
Voice mode decides how the tick count of the notes is enforced vs. the time signature.  SOFT means it is not enforced.  FULL means it can be > the number of ticks but not less.  STRICT is the default, means it must match exactly.  So the error message was telling you the correct thing, but it probably wasn't obvious why Formatter.FormatAndDraw does something different that Formatter().joinVoices.Format.  I always set voice to SOFT, I wish it were the default.

Adding an 'about Voice and Formatter' section, similar to the 'Renderer and context' section, might be useful.     I would not object to having all the tutorials use the Voice+Formatter method of the first 2 sections.

> Accidental.applyAccidentals() which is pretty hard to find otherwise.

I think if we are after consistency in the documentation, we would stick with the note.addModifier approach for the basic tutorial, since it works for all modifiers.  The idea is that we're showing people how to format things they way they want, and not assume what it means when an accidental is (or is not) applied to a pitch that is also in the key signature.  Like with FormatAndDraw, it does some things for you but it also hides some parts of the API you might be interested in.

**Comment by rvilarl** [comment]
@stevage have you seen step3 in https://vexflow.github.io/vexflow-examples/tutorial/index.html ? Is this one fine?

**Comment by stevage** [comment]
>Voice mode decides how the tick count of the notes is enforced vs. the time signature. SOFT means it is not enforced. FULL means it can be > the number of ticks but not less. STRICT is the default, means it must match exactly. So the error message was telling you the correct thing, but it probably wasn't obvious why Formatter.FormatAndDraw does something different that Formatter().joinVoices.Format. I always set voice to SOFT, I wish it were the default.

It seems that my misunderstanding was rooted in the fact that I thought the process for adding a dotted half-note was to add a note with duration `h` then add a dot, whereas you actually need to add a note with duration `hd` and then also add a visual dot.  I'm not sure where, if anywhere, there is documentation telling you to add a `d`. Certainly not intuitive.

Also, this part of step 3 is particularly egriegious:

```
dotted(
        new StaveNote({
            keys: ["eb/4", "d/5"],
            duration: "h",
        }),
        0 /* add dot to note at index==0 */
    ),
```

This part is definitely setting up the newcomer for failure. Not only does it not add the `d` to actually change the note duration, it for some reason uses an example of two notes on the same stem with two different lengths (only one of them is dotted) not even using separate voices. I don't know if this situation is ever musically valid, but it certainly shouldn't be in the beginner's tutorial IMHO.

It then says:

> Notice that in the above example, even though we set the note names and durations correctly, we explicitly request the rendering of accidentals and dots.

I don't understand this. Depending on how you count the stem with a half note and a dotted half note on it, you end up with a 4/4 bar with either 4.5 or 5.5 beats - neither of which is correct. (Or maybe it's saying the note durations were correct before we messed them up by adding visual dots - but this does not seem like a helpful lesson in step 3 of the beginner's tutorial.)

And:

> This allows us to decouple rendering logic and notational semantics. 

It really isn't so much "allows us to" but "forces us to", and as a newcomer, this does not feel like a good thing at all. Displaying a dot for a note that is not calculated as dotted, or vice versa, both seem like extreme edge cases that I can't really imagine ever approaching. If there was an option to un-decouple these two things I would enable it.


@rvilarl 

> have you seen step3 in https://vexflow.github.io/vexflow-examples/tutorial/index.html ? Is this one fine?

It appears to be the same? So, with the same issues.

**Comment by rvilarl** [comment]
> > have you seen step3 in https://vexflow.github.io/vexflow-examples/tutorial/index.html ? Is this one fine?

> It appears to be the same? So, with the same issues.

There is no `Formatter.FormatAndDraw(context, stave, notes);`

**Comment by stevage** [comment]
Oh thanks, I missed that, was a bit focussed on the dot issue. Yes, I think it's better this way because the code flows better from step 2.
