### ISSUE TITLE
Vexml issues

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#176]
@jaredjj3 I moved to Berlin now! Could you list the topics that you would like me to address?

**Comment by jaredjj3** [comment]
Awesome! I'm happy to hear that :) I'll come up with a prioritized list by tomorrow.

**Comment by jaredjj3** [comment]
I went through my history and these are the top 3 that come to mind:

- Figure out what's needed to prevent rests from colliding with notes on different voices ([example1](https://private-user-images.githubusercontent.com/19232300/304446066-fcb63ac6-799e-4b26-9199-de5ef2cc060e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDEzODUsIm5iZiI6MTcwOTY0MTA4NSwicGF0aCI6Ii8xOTIzMjMwMC8zMDQ0NDYwNjYtZmNiNjNhYzYtNzk5ZS00YjI2LTkxOTktZGU1ZWYyY2MwNjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEyMTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YWM0MTFmNmI3MTBiNjQwMjI2YzNjNDViZTViNTQ2N2FjN2UzMTYxMTlhNGM5MTY3MmQzZmIxZjE0Nzk5YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.taFaN3J21uAEHu3i6xOGvxT_BWhuzIWayHc9zaDSDHc), [example2](https://raw.githubusercontent.com/stringsync/vexml/master/tests/integration/__image_snapshots__/complex_formatting_900px.png)). I imagine there's a way to make this work already.
- https://github.com/0xfe/vexflow/issues/1611
- https://github.com/0xfe/vexflow/issues/1607 (I think this is a big ask)

**Comment by rvilarl** [comment]
> * Figure out what's needed to prevent rests from colliding with notes on different voices ([example1](https://private-user-images.githubusercontent.com/19232300/304446066-fcb63ac6-799e-4b26-9199-de5ef2cc060e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDEzODUsIm5iZiI6MTcwOTY0MTA4NSwicGF0aCI6Ii8xOTIzMjMwMC8zMDQ0NDYwNjYtZmNiNjNhYzYtNzk5ZS00YjI2LTkxOTktZGU1ZWYyY2MwNjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEyMTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YWM0MTFmNmI3MTBiNjQwMjI2YzNjNDViZTViNTQ2N2FjN2UzMTYxMTlhNGM5MTY3MmQzZmIxZjE0Nzk5YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.taFaN3J21uAEHu3i6xOGvxT_BWhuzIWayHc9zaDSDHc), [example2](https://raw.githubusercontent.com/stringsync/vexml/master/tests/integration/__image_snapshots__/complex_formatting_900px.png)). I imagine there's a way to make this work already.

I believe that there is a bug. Overlapping rests are being shifted by a fix value. @ronyeh I will raise a PR for that.

**Comment by jaredjj3** [comment]
<img width="392" alt="image" src="https://github.com/vexflow/vexflow/assets/19232300/31e19e1e-bae9-4555-8dcb-705c7a1a5dd4">

@rvilarl, do you think it also makes sense for the formatter to be responsible for collisions like this, or is this intentionally up to the caller? It would be nice if I didn't have to detect and format that.

**Comment by rvilarl** [comment]
I agree it would make sense. @mscuthbert is doing a formatter review, formatter is obscure for all of us. 

The rests collisions is also being more complex than I expected.

**Comment by jaredjj3** [comment]
Hey @rvilarl, in https://github.com/stringsync/vexml/pull/225, I switched from rendering my own measure numbers to letting vexflow render them. They render correctly for staves, but incorrectly for tabs (measure numbers are too big). I'm on `5.0.0-alpha.3`.

<img width="694" alt="image" src="https://github.com/vexflow/vexflow/assets/19232300/e86f748d-d6be-4466-b77d-91c017a488f0">

Other examples:

- [tabs_basic_900px.png](https://github.com/stringsync/vexml/blob/feef670db42d9359cc5fb63382dea411e805c737/tests/integration/__image_snapshots__/tabs_basic_900px.png)
- [tabs_dead_notes_900px.png](https://github.com/stringsync/vexml/blob/feef670db42d9359cc5fb63382dea411e805c737/tests/integration/__image_snapshots__/tabs_dead_notes_900px.png)

FWIW, the font info seems wrong. For `TabStaves`, when I inspect the tab info, I get:

```json
{
    "family": "Bravura,Academico",
    "size": 30,
    "weight": "normal",
    "style": "normal"
}
```

For normal `Staves`, I get

```json
{
    "family": "Bravura,Academico",
    "size": 30,
    "weight": "normal",
    "style": "normal"
}
```

It doesn't seem I can customize the measure number text ([code](https://github.com/vexflow/vexflow/blob/f479c8d3230ca48e8e963469b580de75bcd6bac9/src/stave.ts#L727C14-L727C25)). Does this seem like a bug or am I doing something wrong?

**Comment by rvilarl** [comment]
Thanks Jared. I will look into that.

**Comment by rvilarl** [comment]
Topics moved to independent issues.
