### ISSUE TITLE
Annotation width - Justification backwards

### ISSUE THREAD

**Issue by mscuthbert** [vexflow/vexflow#178]
As I'm making bigger and bigger "annotations" with lyrics, I think that the computation of width is incorrect for LEFT or RIGHT justification:

```typescript
if (annotation.horizontalJustification === AnnotationHorizontalJustify.LEFT) {
    maxLeftGlyphWidth = Math.max(glyphWidth, maxLeftGlyphWidth);
    leftWidth = Math.max(leftWidth, textWidth) + Annotation.minAnnotationPadding;
} else if (annotation.horizontalJustification === AnnotationHorizontalJustify.RIGHT) {
    maxRightGlyphWidth = Math.max(glyphWidth, maxRightGlyphWidth);
    rightWidth = Math.max(rightWidth, textWidth);
}
```

this says that if we are left justified, that the amount of space to the left needs to be increased.  But really if we are left justified then the amount of space to the RIGHT needs to be increased.  And vice-versa.  So we can reverse the enums.

```typescript
if (annotation.horizontalJustification === AnnotationHorizontalJustify.RIGHT) {
    maxLeftGlyphWidth = Math.max(glyphWidth, maxLeftGlyphWidth);
    leftWidth = Math.max(leftWidth, textWidth) + Annotation.minAnnotationPadding;
} else if (annotation.horizontalJustification === AnnotationHorizontalJustify.LEFT) {
    maxRightGlyphWidth = Math.max(glyphWidth, maxRightGlyphWidth);
    rightWidth = Math.max(rightWidth, textWidth);
}
```

the default case of CENTER_STEM (or CENTER) is unchanged, which is why it escaped notice till now.

Similar code appears in ChordSymbol also, but I haven't tested it to see if it fixes it.

Testing with the longest one-syllable  English word.  Before:
<img width="275" alt="Screenshot 2024-03-07 at 10 24 57" src="https://github.com/vexflow/vexflow/assets/3521479/0291b89e-4942-442e-bd56-e702c8612b5f">

After:
<img width="235" alt="Screenshot 2024-03-07 at 10 25 08" src="https://github.com/vexflow/vexflow/assets/3521479/e50c949a-151c-414a-b8e5-4199b024c4aa">

**Comment by AaronDavidNewman** [comment]
Dang, you're right.  It was done exactly backwards (also in Draw).  Good catch!

That code actually predates even separating the horizontal and vertical justification.

**Comment by rvilarl** [comment]
@mscuthbert are you planning to submit a PR to close that?

**Comment by mscuthbert** [comment]
sure thing.  I just have to get a VF5 dev environment going which I no longer have.

**Comment by AaronDavidNewman** [comment]
I just updated the PR comments, but I see now how this happened.  Left-justified just means that the text is justified on the left-most column of text.  According to that interpretation, the original behavior was correct.  But it's a separate issue from where the alignment starts from.  In other words, alignment of the text and offset of the text are different things.

**Comment by rvilarl** [comment]
@AaronDavidNewman do you mean that we have to roll back this change?

**Comment by AaronDavidNewman** [comment]
no, this change is good.
