### ISSUE TITLE
ctx.applyStyle()/removeStyle() should always push a state

### ISSUE THREAD

**Issue by mscuthbert** [vexflow/vexflow#194]
From #189 discussion (edited for tense)

> Make applyStyle() and removeStyle() go ahead and do a ctx.save()/ctx.restore() if there is a context defined whether or not style is defined.  It seems like the small overhead of keeping an extra state-push/pop is worth it for avoiding the subtle bugs that occur when state isn't fully restored.

Endorsed by @AaronDavidNewman 

Entails moving the check for defined `this.style` to after `setState()`/`restoreState()` and removing `setState()`/`restoreState()` from methods that also call `applyStyle()`/`removeStyle()` in their code.

**Comment by rvilarl** [comment]
We should look at performance impact. @AaronDavidNewman is there a way to formalize performance tests of #38?

**Comment by AaronDavidNewman** [comment]
I could, is this change checked in on a branch?

You can get the renderer performance app https://github.com/AaronDavidNewman/VexRender and just drop any vex version into one of the targets to compare it.  If I can find this change, I will do that :)

**Comment by rvilarl** [comment]
I have been investigating this topic:
- `RenderContext` `save()` & `restore()` saves not only the style, but also the font.
- we are using `save()` & `restore()` in `apply/restoreStyle` and also when we change fonts with `setFont()`

I agree to always push a state whether or not style is defined as suggested by @mscuthbert, but, we should avoid to do it twice. One for the font and one for the style.

Without the style check, `restoreStyle()` is a `RenderContext` `save()`

I suggest to remove `save()` from `applyStyle()` remove all calls to `restoreStyle()` and use `save()` & `restore()` directly.

@mscuthbert @AaronDavidNewman @ronyeh thoughts?
