### ISSUE TITLE
Support external embedding with QuickJS and custom graphics drawing

### ISSUE THREAD

**Issue by nwhitehead** [vexflow/vexflow#198]
Love VexFlow!

I'm working on integrating VexFlow into the Godot game engine. The goal is to allow games and "game-like" applications related to music to show sheet music with cursors etc. This would be both for the game editor (pre-rendering images of music as assets for the game) and for in-game display (render based on user actions during gameplay).

My approach right now is to use [QuickJS](https://bellard.org/quickjs/) for the JavaScript interpreter. Then I have some JavaScript wrapper code that sets up a fake document object and fake canvas. The drawing commands are then intercepted and turned into Godot drawing commands of the appropriate kind.

In the previous version of VexFlow I was getting Bezier points through the canvas context and trying to render those. As you might imagine fonts have their own world of craziness so I was having trouble with holes, self intersection etc. But with the new version (5) I get text draw commands which I can match up with direct Godot font rendering. It works much better now.

I guess this issue is a request to support this workflow. Right now I don't see any blockers but some developer documentation about what needs to be stubbed out and intercepted would be helpful. A test that breaks if this workflow breaks would also be great.

I think the test could be a simple command line C++ program that does offline rendering using QuickJS and some simple C++ drawing libraries. That way the test would break if JavaScript code suddenly used a previously unused canvas context drawing method or something similar.

Let me know what you think. I'm willing to help share what I've done for this and write a test but I'm not that familiar with the VexFlow code so it would probably need quite a bit of review.

**Comment by rvilarl** [comment]
Hi, make a PR with the test and let us see how it looks. :)

**Comment by nwhitehead** [comment]
Still working on an actual rendering test, but making progress.

I switched to Rust for the renderer. I'm using QuickJS as the interpreter, tiny-skia for path rendering, and ab_glyph for font rendering. As I work through the examples and tutorials I keep hitting small bits of functionality that are missing. But right now the code supports Bravura and Academico fonts, zoom factor for scaling, Factory and low-level VexFlow interface, fractional font sizes, italics, quadratic curves (for ties), erasing for tab numbers, somewhat correct font metrics.

The challenge is that doing everything the browser supports requires basically implementing a web browser. This is the node-canvas approach. I want something much lighter, but then what is the specification? I think the ideal specification is working tests rather than a text document that no-one wants to read. So my focus next is on getting the full test suite in `tests/` to run through the renderer.

Right now the code is in a separate repo: https://github.com/nwhitehead/vexflowrust
