### ISSUE TITLE
Scaling SVG doesn't work when calling `context.clear()`

### ISSUE THREAD

**Issue by alindsay55661** [vexflow/vexflow#202]
I am testing `"vxflw-early-access": "5.0.0-alpha.0"` and running into bizzare scaling issues. Here is the correct output at a `scale` factor of `1`.

![image](https://github.com/vexflow/vexflow/assets/270710/23a44dbb-8f7b-4013-a29d-8f3391f9f4a7)

![image](https://github.com/vexflow/vexflow/assets/270710/cdb14857-b3a3-4fb9-93eb-c568dfde1932)

When setting `width` and `height` like so to a `scale` factor of `0.6`:

```ts
renderer.resize(width * scale, height * scale)
renderer.getContext().scale(scale, scale)
```

The SVG output applies the correct `width`, `height` and `style` attributes. But the `viewbox` is completely messed up.

![image](https://github.com/vexflow/vexflow/assets/270710/0246b737-281f-4fb4-a7a1-12b4b5345fb8)

![image](https://github.com/vexflow/vexflow/assets/270710/27a5be60-d6a5-4865-afd4-10b8e58db426)

If I omit the `scale()` call:

```ts
renderer.resize(width * scale, height * scale)
//renderer.getContext().scale(scale, scale)
```

Then the `viewbox` dimensions are correct, but the image is not scaled in any way - only the bounding dimensions.

![image](https://github.com/vexflow/vexflow/assets/270710/2568c972-6e23-44bb-9045-4119f85ee209)

![image](https://github.com/vexflow/vexflow/assets/270710/bc613d93-2ee5-4d32-9010-7487dbcfdcbc)

I did not experience this issue with v4. Is there a new way to handling scaling in v5?

**Comment by alindsay55661** [comment]
After some debugging, it appears this problem is caused because `context.clear()` makes additional calls to `context.scale()`, thereby scaling it on top of itself (see line 350).

https://github.com/vexflow/vexflow/blob/f479c8d3230ca48e8e963469b580de75bcd6bac9/src/svgcontext.ts#L334-L351

In my case, I am clearing the context on each note/chord to start with a blank staff. The result is that scaling gets out of control. Is it intended to destroy and create a brand new renderer every time in order to preserve the scaling attribute? I would expect `clear()` to simply clear the canvas, not perform scaling operations.

**Comment by alindsay55661** [comment]
For now, I am hacking around the problem locally by referencing "private" properties:

```ts
// Reset the render
// context.clear() // Currently causes scaling issues
// @ts-expect-error - use of private property
while (context.svg.lastChild) {
  // @ts-expect-error - use of private property
  context.svg.removeChild(context.svg.lastChild)
}
```

**Comment by AaronDavidNewman** [comment]
This looks like it's in 4.0 also.  I don't think any of our test cases use 'clear' method of render context.

In my experience, if you want to use SVG for any realistic application, you need to access the SVG element directly at some point.  Canvas doesn't have anything like a viewbox, so there is no way to make a generic rendercontext interface that works consistently to handle scaling.  The scale method of the render context implicitly assumes you're calling it before rendering anything.  Even if you call it (scale) more than once, the interface doesn't make it clear - do you want the scale your asking for, or to scale the existing value?
