### ISSUE TITLE
Unison notehead accidental collision with stems down

### ISSUE THREAD

**Issue by mscuthbert** [vexflow/vexflow#210]
When stems go down, it appears that two-notehead augmented unisons have overlap between accidental and the left notehead.  

Report from Joseph VanderStel

```typescript
const note_obj = new VF.StaveNote({
    "keys":["Bn/5","B#/5"],
    "duration":"h",
    "stemDirection":-1,
});
note_obj.addModifier(new VF.Accidental('n'), 0);
note_obj.addModifier(new VF.Accidental('#'), 1);
```
<img width="97" alt="Screenshot 2024-06-27 at 00 54 36" src="https://github.com/vexflow/vexflow/assets/3521479/3836db24-0bc3-4f67-ba0e-566015d1cf16">

**Comment by rvilarl** [comment]
@mscuthbert I can not see the screenshot

**Comment by mscuthbert** [comment]
> @mscuthbert I can not see the screenshot

Sorry!  We first discussed this in a private repo -- I guess you can't reuse images from there.  It is fixed above and now posted here.

<img width="97" alt="Screenshot 2024-06-27 at 00 54 36" src="https://github.com/vexflow/vexflow/assets/3521479/2356ff31-d1af-4dee-8c08-d5c87dfe1e13">

**Comment by vanderstel** [comment]
This may have been an issue from the very beginning. I can confirm it goes back at least to v1.2.75.

**Comment by rvilarl** [comment]
Thanks I will look into that
