### ISSUE TITLE
SVGContext: structuredClone is not defined

### ISSUE THREAD

**Issue by jaredjj3** [vexflow/vexflow#211]
On vexflow `5.0.0-alpha.4`, I'm getting the following error, but only in my test environment.

```
    Error name:    "ReferenceError"
    Error message: "structuredClone is not defined"

          35 |     }
          36 |
        > 37 |     vfContext.save();
             |               ^
          38 |
          39 |     vfContext.scale(1, 1);
          40 |

      at It.structuredClone [as save] (node_modules/vexflow/build/cjs/webpack:/VexFlow/src/svgcontext.ts:434:20)
      at Text.save (src/drawables/text.ts:37:15)
```

https://github.com/vexflow/vexflow/blob/b71510759a0805f5a61170a47ec293256833eb35/src/svgcontext.ts#L579

After digging, it seems that [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) is not defined in my test environment (https://github.com/jsdom/jsdom/issues/3363).

This outcome surprised me, especially since I didn't know `structuredClone` was a Web API. Do you think this warrants any documentation?

**Comment by rvilarl** [comment]
@jaredjj3 which baseline are you using? It says baseline 2022, newly available.

Is there anything that you expect me to do in vexflow?

**Comment by jaredjj3** [comment]
Thanks, I'll try that! This is more of a heads up in case other folks bring this up.

**Comment by jaredjj3** [comment]
For anyone else looking for a solution, this worked: https://github.com/jestjs/jest/issues/14835#issuecomment-1880512776
