### ISSUE TITLE
ApplyStyle in derived classes from Element

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#223]
This exercise has made me realise that some elements apply style already on `draw()`. What is the need of `drawWithStyle()`then? Should it be deleted?
@mscuthbert @AaronDavidNewman @ronyeh what do you think should it drawWithStyle be deleted or should we refactor the style out of draw?

_Originally posted by @rvilarl in https://github.com/vexflow/vexflow/issues/220#issuecomment-2226974080_

**Comment by rvilarl** [comment]
I have investigated the classes deriving from `Modifier`:
- there 15 classes that derive from `Modifier`
- `Annotation`, `Bend`, `ChordSymbol`, `Ornament` call `applyStyle()` in `draw()`
- `Bend` calls `applyStyle()` three times.

My first idea was to remove the calls and use `drawWithStyle()`, however, `Bend` does require the three calls and that does not fit to `drawWithStyle()`. I also believe that we should always call `applyStyle()`.

I suggest to delete `drawWithStyle` and call consistently `applyStyle()` in `draw()`

@ronyeh @AaronDavidNewman @mscuthbert @jaredjj3 what do you think?

**Comment by ronyeh** [comment]
Hi Rodrigo,

I haven’t had a chance to follow these recent PRs. I will take a look
tomorrow.

But overall, if you think this is a really important change for 5.0, then
we can include it. Otherwise, if it is low enough priority, can it wait for
5.1?

Just want to make sure we don’t have too much feature creep. Otherwise
we’ll never ship.

Probably the most important things we need to do is document more the
differences between 4.x and 5.x, and write up a simple migration guide.
Ideally, most basic examples from 4.x “just work” with no changes.

Ron

**Comment by rvilarl** [comment]
> Hi Rodrigo, I haven’t had a chance to follow these recent PRs. I will take a look tomorrow. But overall, if you think this is a really important change for 5.0, then we can include it. Otherwise, if it is low enough priority, can it wait for 5.1?

Hi Ron, the styling topic is quite messy: done in different ways and also not available on all classes. I think that it  would be good to agree on a standard way for VexFlow 5. 

> Just want to make sure we don’t have too much feature creep. Otherwise we’ll never ship. Probably the most important things we need to do is document more the differences between 4.x and 5.x, and write up a simple migration guide. Ideally, most basic examples from 4.x “just work” with no changes. Ron

To do that I think that we should re activate the documentation and document the changes in the api. Do you still want to make a separted vexflow-doc? we can go class by class looking at and documenting the API changes.

**Comment by rvilarl** [comment]
> I too am a bit concerned about removing methods without a migration/deprecation process.
> 
> It's not always possible, but generally I think software should go from "1 not ideal way of doing it" to "2 ways of doing it: one new and great and one old and not ideal" to "2 ways: the old way is marked as deprecated with a documented way of moving to the new way" to "1 great way of doing it". So most mature software takes 3 versions to get rid of the old.

Hi Michael, thanks for the proposal, I will follow the 3 steps approach.

> Vexflow is too integrated in what I do to upgrade if it risks breaking everything. The font change is already so risky (I have to uninstall bravura on my own system to be sure things are working for my users) that anything else that is potentially breaking makes v5 seem like a "maybe I should skip upgrading" kind of release.

Are you already using V5 with your users? This would be great news for me!

**Comment by rvilarl** [comment]
I will try to justify why I say that it is messy. Let us look deeper into the rendering of `Modifier` together with `StaveNote`.

The rendering starts in `Factory.draw()` which renders the score with styles but is calling `draw()` methods and not `drawWithStyle()`

https://github.com/vexflow/vexflow/blob/5aa39512150a7b33137d649be2ac5e28efcc7d1d/src/factory.ts#L682-L694

The rendering continues in `Voice.draw()`. `Voice` is an `Element` that has its own style. Here I observe the following problems:
- `Voice.draw()` does not call `applyStyle()` which is as expected and `Factory.draw()` did not call `Voice.drawWithStyle()`. As a consequence **voice styling is being ignored**.
- `Voice.draw()` which should be style agnostic is calling `Tickable.drawWithStyle()` which is not. This is messy but if we called `Tickable.draw()`, `voice.drawWithStyle()` would also call `Tickable.draw()` which would not render styled tickables.  

https://github.com/vexflow/vexflow/blob/5aa39512150a7b33137d649be2ac5e28efcc7d1d/src/voice.ts#L287-L302

The rendering continues in `StaveNote.draw()`. Here I observe the following problems:
- `StaveNote.draw()` does call `applyStyle()`. As a consequence, **the context is gonna be saved twice** as `StaveNote.drawWithStyle()` was called by `Voice.draw()`.

https://github.com/vexflow/vexflow/blob/5aa39512150a7b33137d649be2ac5e28efcc7d1d/src/stavenote.ts#L1218

The rendering continues in `Voice.drawNoteHeads()`. Here I observe the following problems:
- `Voice.drawNoteHeads()` which should be style agnostic as it is instantiated by  `StaveNote.draw()` is calling `applyStyle()` which is not. This is messy but necessary to get the score rendered with styled noteheads.  

https://github.com/vexflow/vexflow/blob/5aa39512150a7b33137d649be2ac5e28efcc7d1d/src/stavenote.ts#L1120-L1131

The rendering continues in `Voice.drawModifiers()`. Here I observe the following problems:
- `Voice.drawModifiers()` which should be style agnostic as it is instantiated by  `StaveNote.draw()` is using `notehead.applyStyle()` and `modifier.drawWithStyle()` which are not. This is messy but once again necessary to get the score rendered with styled modifiers.
- Calling `noteHead.applyStyle()` is unnecessary as we are within the `notehead` group started in `Voice.drawNoteHeads()`. This is **an unnecessary context storage**.
- Finally calling `modifier.drawWithStyle()` will cause **a double context storage** in `Annotation`, `Bend`, `ChordSymbol`, `Ornament` which also call `applyStyle()` in `draw()`

https://github.com/vexflow/vexflow/blob/5aa39512150a7b33137d649be2ac5e28efcc7d1d/src/stavenote.ts#L1070-L1085

**Comment by rvilarl** [comment]
I believe that `draw()` methods should consistenly call `applyStyle()` it is not possible to make these methods style agnostic.

**Comment by rvilarl** [comment]
In the end, I have prepared a PR that I will upload once #220 is merged. I have removed the main call to `applyStyle()` in `draw()` and replaced the calls to `draw()` by `draw wIthStyle()`
