### ISSUE TITLE
Use friendly names for SMUFL glyphs (e.g., use a const enum for codepoints)

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow#23]
I'll assign this to myself.

Consider using `const enum` to allow us to reference SMuFL code points in a more readable way.

See: https://www.typescriptlang.org/docs/handbook/enums.html#const-enums
> ...unlike regular enums they are completely removed during compilation. Const enum members are inlined at use sites. 

See: https://github.com/w3c/smufl/blob/gh-pages/metadata/glyphnames.json

Using the `const enum` could look like:

```
smufl.coda => E048
smufl.codaSquare => 0xE049
smufl.codaAlternate => 0x1D10C
```

I wasn't sure how to capitalize the acronym.

The official format is `SMuFL` with the lowercase `u`. We could simplify it with all caps: `SMUFL` or only do the first letter... `Smufl`. Or all lowercase?

**Comment by ronyeh** [comment]
See this discussion: https://github.com/vexflow/vexflow/pull/48/files#r1298762764

**Comment by ronyeh** [comment]
Linking to the discussion here: https://github.com/vexflow/vexflow/pull/35#discussion_r1313818613

**Comment by ronyeh** [comment]
I'm also going to link this exploratory work here: https://github.com/vexflow/vexflow/pull/30

**Comment by ronyeh** [comment]
@rvilarl and @0xfe and anyone else who might be interested, such as @AaronDavidNewman 

We are discussing how we can best use friendly readable SMuFL names in the VexFlow 5 library, without hugely inflating the library size if possible.

Mohit left some comments here: https://github.com/vexflow/vexflow/pull/35#discussion_r1314252447

I see a few options:

1. Include the entire SMuFL friendly names => code points mapping in our library. In the grand scheme of things it probably won't slow down websites all that much. Most web apps are huge these days.
2. Include only the subset of SMuFL codes that we use internally in VexFlow. This is much much smaller, because the entire SMuFL spec includes really rare glyphs that everyday scores won't use.
3. Don't include any SMuFL friendly names. We only accept Unicode characters. This results in the lightest library which some folks like Simon like. We could offload the friendly names into an external library.

Also, we need to continue exploration of `const enum` in TypeScript. The basic idea is that they act like C `#define` where TypeScript compilers will remove the variable name during compilation, and replace the long friendly names with the unicode characters directly.

More to come....

**Comment by AaronDavidNewman** [comment]
I think it makes sense for each module to expose friendly names that map to the smufl codes.  We shouldn't make people send hex codes from their own application into Vex.  We don't make people send 1,2 etc. for position IDs.  I've never used a library that didn't have identifiers for constants. 

Maybe this is an aside, but what is the gain we get from optimizing for the size of our pre-compiled source code?  Since about the 1980s, it isn't something I've ever thought about.

**Comment by ronyeh** [comment]
We can always include all the smufl names as a big enum and see what the
final impact is on the library size, after gzip.

Some folks like (Simon at OSMD) have expressed concerns in the past with
font sizes bloating the vexflow library size.

In practice it probably doesn't make a huge difference since adding a few
images to a web app will already have a bigger network impact than
downloading the vexflow library.

I'd vote for finishing up the current migration using only Unicode strings.
Then we can add the entire smufl name list and see how much bigger it makes
the library. If folks don't like it, we can ship a subset by default and
have an optional way to import the entire list.

**Comment by 0xfe** [comment]
> I'd vote for finishing up the current migration using only Unicode strings. Then we can add the entire smufl name list and see how much bigger it makes
the library. 

If you're pretty far in, that sounds fine. However, it feels like a premature optimization. My (soft) preference would be Rodrigo's option 3 from #35 (ship two releases, one with all symbols, and the other with the bare minimum[^1]) -- this provides usability by default, which you can then optimize over time (e.g., implementing a separate `vexflow-ext-smufl` package.)

[^1]: By "bare minimum", I mean only the code points that are used in the VexFlow source code.

**Comment by ronyeh** [comment]
Sounds good. We will figure out a way to ship all glyph names + minimal glyph names.


For now we will defer to what Rodrigo prefers since he is doing all the coding. 

One idea @rvilarl if you are OK with it. For any future classes that you port, can you add a (non exported) const enum at the top of the ts file that includes all the smufl glyphs used by that file?

```
const enum smufl {
  gClef = ...,
  fClef = ...,
  ...
}
```

Then that class can use the enum in the code below. 

Once all the v5 work is done we can examine the tops of each class to determine what the minimal set of smufl glyphs is.

**Comment by 0xfe** [comment]
That sounds good. I did a scan of the codebase, and found this across `src/` and `tests/` (dumped into a TS const):

```typescript
export const CODES = {
  dynamicForte: '\uE522',
  dynamicPiano: '\uE520',
  dynamicMezzo: '\uE521',
  dynamicSforzando: '\uE524',
  dynamicZ: '\uE525',
  dynamicRinforzando: '\uE523',
  csymParensLeftTall: '\u0028',
  csymParensRightTall: '\u0029',
  csymParensLeftVeryTall: '\u0028',
  csymParensRightVeryTall: '\u0029',
  tremolo1: '\uE220',
  keyboardPedalPed: '\uE650',
  keyboardPedalUp: '\uE655',
  segno: '\uE047',
  ornamentTrill: '\uE566',
  ornamentMordent: '\uE56D',
  ornamentShortTrill: '\uE56C',
  coda: '\uE048',
  caesura: '\uE4D1',
  caesuraCurved: '\uE4D4',
  breathMarkComma: '\uE4CE',
  breathMarkTick: '\uE4CF',
  ornamentTurn: '\uE567',
  ornamentTurnSlash: '\uE569',
  gClef: '\uE050',
  fClef: '\uE062',
  cClef: '\uE05C',
  unpitchedPercussionClef1: '\uE069',
  SixStringTabClef: '\uE06D',
  repeat1Bar: '\uE500',
  repeat2Bars: '\uE501',
  repeat4Bars: '\uE502',
  repeatBarSlash: '\uE504',
  gClef8va: '\uE053',
  fClef8va: '\uE065',
  gClef8vb: '\uE052',
  fClef8vb: '\uE064',
  noteheadParenthesisRight: '\uE0F6',
  noteheadParenthesisLeft: '\uE0F5',
};
```

**Comment by 0xfe** [comment]
Also for posterity, you can run this command to find uses of unicode, and which files to update:

```bash
$ grep -E -r "['\"]\\\\u[0-9A-F]+['\"]" src tests

src/parenthesis.ts:      this.text = '\uE0F6'; /*noteheadParenthesisRight*/
src/parenthesis.ts:      this.text = '\uE0F5'; /*noteheadParenthesisLeft*/
src/stemmablenote.ts:          : glyphProps.codeFlagUp ?? '\u0000';
src/articulation.ts:      '\u0000';
src/note.ts:    if (codeNoteHead !== '\u0000') {
src/timesignature.ts:    let code = '\u00000';
src/tuplet.ts:      denominator = '\uE88A' /* tupletColon */ + denominator;
src/repeatnote.ts:  '1': '\uE500' /*repeat1Bar*/,
src/repeatnote.ts:  '2': '\uE501' /*repeat2Bars*/,
src/repeatnote.ts:  '4': '\uE502' /*repeat4Bars*/,
src/repeatnote.ts:  slash: '\uE504' /*repeatBarSlash*/,
src/repeatnote.ts:    const glyphCode = CODES[type] || '\uE500'; /*repeat1Bar*/
src/tables.ts:    return '\u0000';
src/clef.ts:        code: '\uE050' /*gClef*/,
src/clef.ts:        code: '\uE062' /*fClef*/,
src/clef.ts:        code: '\uE05C' /*cClef*/,
... snipped ...
```
