### ISSUE TITLE
Separate repository for API docs?

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow#4]
Should we have a `docs` repo to store the generated API docs? That way, we can update them every time there is a release. And the docs could be tagged with each release number.

Right now, there is a slightly annoying issue where every time we submit a new PR, it comes along with a huge bunch of changes in the `docs/` directory, since the API changed.

**Comment by rvilarl** [comment]
I would not separate docs in another repo but I would also not update the docs in every PR. In fact I would do Docs update only PRs like we did in the past. As you said, having docs updates in PRs that have to be reviewed is very annoying.

**Comment by ronyeh** [comment]
OK, I'm fine keeping it in the same repo for now. However, I'm a huge fan of the Godot organization, and would happily copy any of their best practices if they would help us. They do happen to have a separate repo for their docs, and their docs are very extensive and well done: https://github.com/godotengine/

One issue I have encountered is when I review a PR and merge it, the docs are temporarily "out of sync" with the repo. 

Honestly, I'd rather just submit the docs/api changes along with the same PR. When reviewing via the GitHub user interface, we can just ignore anything under the docs/ folder.

That way, the docs are always correct and up to date with respect to the state of the repository.

**Comment by ronyeh** [comment]
https://github.com/vexflow/docs

Eventually we will move the docs/api over to the docs repo. That way we can update them whenever we release new versions of vexflow. 

https://github.com/vexflow/fonts
