### ISSUE TITLE
Document How to Get Started w/ VexFlow with Web Fonts

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow#60]
Assumptions:
- Developer has no SMuFL fonts on their system.
- End user has no SMuFL fonts on their system.

What are the minimal steps required to get a webpage showing a basic score? The network traffic for the minimal demo should load only a single web font (Bravura or Leland or Gonville).

---

Previously Discussed in #46

@rvilarl Yes, we are in agreement. I do not believe we should be "embedding" the OTF into the library.

What I meant is that we need to make it super duper easy for a developer to use VexFlow. 

For example, if a developer wants to use V5 and ONLY load GonvilleSmufl, they should not have to load all the other web fonts that are included in the `loadWebFonts()` method.

What would be the best process for a developer to do this? We need to document this. Ideally, it could look something like this:

```
// ... include the vexflow.js in a script tag ... this library is very small and contains zero fonts.

// This line loads the GonvilleSmufl font from the jsDelivr CDN. No other fonts are loaded.
await Vex.Flow.Font.loadWebFont('Gonville');

// Set the default music engraving font.
Vex.Flow.setMusicFont('Gonville');

// Do other stuff....
....
```

Maybe the setMusicFont() and loadWebFont() should be combined into a single line....?

Alternatively, if the developer wants to pre-load their preferred font from their personal server, they can use the CSS `@font-face` rule to load their own WOFF2 file, before initializing VexFlow.

Anyways, I think we need to document the easiest path to get VexFlow working on a completely clean installation (assuming the developer &amp; end user both have no music fonts on their system).

_Originally posted by @ronyeh in https://github.com/vexflow/vexflow/issues/46#issuecomment-1678219134_

**Comment by rvilarl** [comment]
hi @ronyeh,
the approach I like most for the future is to use font-face statements. I did that in the inspection tool `glyphs.html`. But I do not know how to force an await on css. do you?

_Originally posted by @rvilarl in https://github.com/vexflow/vexflow/pull/65#discussion_r1299611638_

**Comment by ronyeh** [comment]
I guess I should continue work on https://github.com/vexflow/vexflow/pull/61 then.... :-)

CSS font-face and the FontFace JS API ultimately do the same thing, but you are correct in that there isn't a pure CSS way to block until the font is loaded before starting up VexFlow.

CSS has `font-display: block;` but I think this only tells the browser to hide the text until the font is completely loaded, to avoid the flash of unstyled text or flash of empty squares.

This might work for SVG output, as the browser should be able to swap the SVG text to the correct font.

This probably won't work for Canvas output. If the browser has already issued the canvas 2D draw commands for the text, I would imagine that it'll just draw empty squares if the font is not yet loaded.

We'll have to set up some tests to check all these edge cases.

**Comment by rvilarl** [comment]
A way to go to document the usage would be to update the tutorials. see https://github.com/0xfe/vexflow/discussions/1292

@jaredjj3  could you help me updating https://jsfiddle.net/ronyeh/c36p8eo2/ ?

**Comment by jaredjj3** [comment]
Sure, I just added the CSS rule:

```css
@font-face {
   font-family: 'Bravura';
   src: url(https://cdn.jsdelivr.net/npm/vexflow-fonts@1.0.6/bravura/Bravura_1.392.otf) format(opentype);
 }
```

https://jsfiddle.net/myznoxw1/

Just note that this couples your documentation with a specific vexflow-font version (unless you can specify @latest in the url). This is probably ok, but just wanted to make you aware of it.

**Comment by rvilarl** [comment]
Documented in README.md and examples provided in vexflow-examples.

**Comment by rvilarl** [comment]
README.md now in a PR.
