### ISSUE TITLE
Gonville vs GonvilleSmufl

### ISSUE THREAD

**Issue by ronyeh** [vexflow/vexflow#74]
In VexFlow 5, will Gonville be an alias for GonvilleSmufl?

I think that every API that accepts the string 'Gonville' should treat it like 'GonvilleSmufl', and the same APIs should accept 'GonvilleSmufl' as well. Otherwise it gets too confusing. So both strings should do the same thing.

So in my current PR I have both Gonville and GonvilleSmufl as keys in the web fonts dictionary:

```ts
  static WEB_FONT_FILES: Record<string /* fontName */, string /* fontPath */> = {
    Academico: 'academico/Academico_0.902.woff2',
    Bravura: 'bravura/Bravura_1.392.woff2',
    BravuraText: 'bravura/BravuraText_1.393.woff2',
    Gonville: 'gonvillesmufl/GonvilleSmufl_1.100.woff2',
    GonvilleSmufl: 'gonvillesmufl/GonvilleSmufl_1.100.woff2',
```

Similarly, setMusicFont() will look like this:
```ts
  static setMusicFont(...fontNames: string[]): Font[] {
    switch (fontNames[0]) {
      case 'Bravura':
        CommonMetrics.fontFamily = 'Bravura,Roboto Slab';
        break;
      case 'Gonville':
      case 'GonvilleSmufl':
        CommonMetrics.fontFamily = 'GonvilleSmufl,Bravura,Roboto Slab';
        break;

```
That way, loadWebFont and setMusicFont will both accept Gonville / GonvilleSmufl as equivalent font names.

**Comment by ronyeh** [comment]
@rvilarl What do you think about this topic? 

Option 1: Just rename your SMuFL version to "Gonville" and treat it like nothing ever changed. The codebase will treat it as "Gonville". 

Option 2: We no longer support the name "Gonville". We will only refer to this new font as "GonvilleSmufl" in every place. So a developer would have to write Vex.Flow.setMusicFont("GonvilleSmufl").


Note that the original font designer says this on his website https://www.chiark.greenend.org.uk/~sgtatham/gonville/:

> Licence
> The Gonville font files themselves may be used without restriction. You don't even have to preserve a copyright notice or anything. Use freely and enjoy.
> 
> In particular, this means that you may embed the Gonville font or portions of it in PostScript, PDF, SVG or other document file formats without incurring any constraint whatsoever on your subsequent use or licensing of those files.
> 
> (On the other hand, if you're using the Gonville outlines in a context where they might be mistaken for your own work, e.g. incorporating them into a music typesetting program, it would be polite to give me credit for the design.)
> 
> The source code that generates the font files (if you download the source archive below, or look in the git repository) is distributed under the MIT licence.
> 
> For more details, see the file called LICENCE in the distribution archive.

**Comment by rvilarl** [comment]
Well my original intention was to call it Gonville but I was told not to do it because the SIL license requires the name to be unique
 This is also why although MuseScore shows Gotville in the GUI, the font in the background is called Gootville.

**Comment by ronyeh** [comment]
Since the original font was not licensed under SIL, can you do the same for
your derivative work? Maybe the license can just say, this is the same as
the original license. Do whatever you want with this font, but it is
optional (but appreciated) if you credit the original font designer (and
editor) in your app/website.

Maybe we should ask the original creator what he'd prefer?

If this is truly just a SMuFL-ized version of his font, I don't see why we
can't just call it Gonville but bump the major version of the font file
(with the blessing of the original designer).

It would make our lives easier if it was just called Gonville.

**Comment by ronyeh** [comment]
I think we should reach out to Simon Tatham / sgtatham to see if he would be okay with us calling this SMuFL-ized version of the font **Gonville**.

We could just bump the major version number of the font, and list Rodrigo as a contributor who mapped the original glyphs designed by Simon to the SMuFL code points. The new version of Gonville will be licensed under SIL.

@rvilarl Let me know if you are OK with this plan.

I can write an email to him to ask if he is okay with this plan. It would be a bit nicer/cleaner if the font was simply called "Gonville" because we wouldn't have to map two names to the same font file.

**Comment by rvilarl** [comment]
@ronyeh yes please reach him

**Comment by rvilarl** [comment]
@ronyeh Gonville is now better than GonvilleSmufl, please proceed with the replacement.
