### ISSUE TITLE
APIs missed after v5 migration.

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow#76]
@AaronDavidNewman @mscuthbert @sschmidtu please add to this issue broken APIs that you would like to be recoverd.

**Comment by rvilarl** [comment]
> For just rendering the music from the saved scores, I just need to know how to map what used to be the glyph names (e.g. csymAccidental) to the unicode that vexflow expects now.  I added those strings to the 'glyphs' structure in chordsymbol.ts in my own branch.  If required, I could move it into smoosic itself. 
>
> To actually interact with the user, and to correctly format the music, I need to know the metrics from the glyph.  There is nothing to call 'GetTextMetrics ' on until I have created the vex objects, which I can't do until I have decided how to layout the music.  Not just for chord changes, if I want to know the width of a clef, for instance,  I'm used to getting the glyph metrics.  I could create the vex objects and save them until I need them, or create a cache for different objects, but I'm not set up to do that right now - I'd have to keep track of them all, or create them all a second time. 
>
> So I'm not going to worry about this part.  I have a vex5 branch of smoosic to generate the test js files with the correct identifiers. I'll continue to develop new Smoosic features against version 4 for now, until there is a reason to switch.

_Originally posted by @AaronDavidNewman in https://github.com/vexflow/vexflow/issues/64#issuecomment-1694384825_

missed APIs;
```
Glyph.getWidth(code: string, point: number, category?: string): number
Glyph.loadMetrics(fontStack: Font[], code: string, category?: string): GlyphMetrics
```
@AaronDavidNewman is that right?

**Comment by AaronDavidNewman** [comment]
For the layout, I need a way to get the width of a glyph.  I got this from xmax - xmin from the glyph (when calculating the width of a clef, for instance).  Glyph height doesn't affect layout as much.

For the text/chord editor in smoosic, I was using:
From the 'glyph' itself, width (xmax - xmin), xmin, the height and  (if available) advanceWidth and leftSideBearing.  For the metrics I used the yOffset and scale (different symbols had different scales for text vs. musical fonts).

I'm not sure about loadMetrics, that must have happened behind the scenes but I only used metrics after they were loaded.

**Comment by rvilarl** [comment]
glyph.ts will be deleted as part of the migration.

_Originally posted by @rvilarl in https://github.com/vexflow/vexflow/pull/34#discussion_r1312545979_

**Comment by AaronDavidNewman** [comment]
For rendering dynamics, I used to do it like this.  This is another thing that won't be possible with Vex 5, due to the absence of glyph and glyph metrics.

I can get something similar with 'renderText' on the TextDynamics object.  But I can't get the dimensions of the text without doing a measurement using getBBox, which I don't want to do here for performance reasons.  Because of this, there's not way to format 'sfz' types of things, horizontally.

I know TextDynamics is a type of TextNote, but using TextNotes is kind of a pain for dynamics, because they function more like a note modifier sometimes.  I want the dynamic to be aligned with a note in the measure, without having to create a whole voice and empty notes to space it correctly.

``` typescript
       const glyphCode = VF.TextDynamics.GLYPHS[ch];
        const glyph = new VF.Glyph(glyphCode, textObj.fontSize);
        glyph.render(this.context.getContext(), x, y);
        x += glyph.getWidth();
        const metrics = glyph.getMetrics();
        textObj.logicalBox = SvgHelpers.boxPoints(x, y + this.context.box.y, metrics.width, metrics.height);
```

**Comment by rvilarl** [comment]
@AaronDavidNewman the following should be possible:
```js
        const glyphCode = VF.TextDynamics.GLYPHS[ch];
        const glyph = new VF.Element();
        glyph.setText(glyphCode);
        glyph.setFontSize(textObj.fontSize);
        glyph.renderText(this.context.getContext(), x, y);
        x += glyph.getWidth();
        textObj.logicalBox = SvgHelpers.boxPoints(x, y + this.context.box.y, glyph.getWidth(), glyph.getHeight());
```

**Comment by AaronDavidNewman** [comment]
Thanks, this works.  VF.Element used to be abstract.

**Comment by rvilarl** [comment]
> Thanks, this works. VF.Element used to be abstract.

Element will supersede Glyph.

**Comment by rvilarl** [comment]
@AaronDavidNewman would you like me to implement an static 'Element.getTextWidth' to provide the functionality given by the static `Glyph.getWidth` I could also use it in #85

**Comment by AaronDavidNewman** [comment]
Sorry I just saw this.  This would be good, if we can do it without causing a repaint.

**Comment by rvilarl** [comment]
@AaronDavidNewman @ronyeh I will include this request to close this issue
